name: Publish Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore src/PhlatQL.Core/PhlatQL.Core.csproj
    - name: Build
      run: dotnet build src/PhlatQL.Core/PhlatQL.Core.csproj --configuration Release --no-restore
    - name: Publish PhlatQL.Core
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/PhlatQL.Core/PhlatQL.Core.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
